In [66]:
import numpy as np
import pandas as pd
from scipy.sparse import lil_matrix, csr_matrix,save_npz,load_npz
from sklearn import svm
from scipy.sparse import hstack
from collections import defaultdict
import json 

In [2]:
def npzToCsv(filename, savename):
    np_Array=np.load(filename)
    arr=np_Array.files[0]
    np.savetxt("Matrix_Data/" + str(savename) + '.csv', np_Array[arr], delimiter=",")

In [3]:
Amatrix = load_npz('Matrix_Data/a_matrix_train.npz')

In [4]:
Bmatrix = load_npz('Matrix_Data/b_matrix_train.npz')

In [5]:
Pmatrix = load_npz('Matrix_Data/p_matrix_train.npz')

In [6]:
Amatrix_test = load_npz('Matrix_Data/a_matrix_test.npz')

In [7]:
BAtrans = Bmatrix*Amatrix.T

In [8]:
ABAtrans_trained = Amatrix*BAtrans

In [9]:
ABAtrans_test = Amatrix_test*BAtrans

In [10]:
df = pd.read_csv('Matrix_Data/training_labels.csv', header=None)

In [11]:
clf = svm.LinearSVC(C=0.1, multi_class = 'ovr', dual = False)

In [12]:
clf.fit(ABAtrans_trained, df[0])


LinearSVC(C=0.1, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, loss='squared_hinge', max_iter=1000,
          multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
          verbose=0)

In [13]:
preds = clf.predict(ABAtrans_test)
type(preds)

numpy.ndarray

In [14]:
type(ABAtrans_test)

scipy.sparse.csr.csr_matrix

In [15]:
df_ABAtrans_test = pd.DataFrame.sparse.from_spmatrix(ABAtrans_test)
df_ABAtrans_test['Prediction'] = preds

In [16]:
Amatrix_test = hstack((Amatrix_test,preds[:,None]))

In [56]:
type(ABAtrans_test)
Amatrix_test.shape
#Amatrix_test = Amatrix_test.todense()
#Printing each app and all apis with pred classification
for i in Amatrix_test:
    print(i)

[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 1]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[0 1 1 ... 0 0 3]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[0 0 0 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]
[[1 1 1 ... 0 0 0]]


In [43]:
type(Amatrix_test)
Amatrix_test.item((140, 235724))
#np.corrcoef()

3

In [67]:
# Opening JSON file 
with open('Matrix_Data/apis.json') as json_file: 
    API_index = json.load(json_file) 

In [72]:
API_index_swap = dict([(value, key) for key, value in API_index.items()]) 
API_index_swap

{0: 'Ljava/lang/String;->endsWith()Z',
 1: 'Ljava/lang/String;->valueOf()Ljava/lang/String;',
 2: 'Ljava/lang/StringBuilder;->append()Ljava/lang/StringBuilder;',
 3: 'Ljava/lang/StringBuilder;->toString()Ljava/lang/String;',
 4: 'Landroid/widget/ImageView;->setImageBitmap()V',
 5: 'Landroid/util/Log;->a()I',
 6: 'Landroid/net/Uri;->parse()Landroid/net/Uri;',
 7: 'Landroid/content/Intent;->setData()Landroid/content/Intent;',
 8: 'Landroid/os/Environment;->getExternalStorageDirectory()Ljava/io/File;',
 9: 'Landroid/graphics/Bitmap;->compress()Z',
 10: 'Ljava/io/FileOutputStream;->flush()V',
 11: 'Ljava/io/FileOutputStream;->close()V',
 12: 'Landroid/content/Intent;->setType()Landroid/content/Intent;',
 13: 'Ljava/io/File;->getPath()Ljava/lang/String;',
 14: 'Landroid/net/Uri;->fromFile()Landroid/net/Uri;',
 15: 'Landroid/content/Intent;->putExtra()Landroid/content/Intent;',
 16: 'Landroid/content/Intent;->createChooser()Landroid/content/Intent;',
 17: 'Ljava/io/FileNotFoundException;->pr

In [83]:
count = 0
API_corelate = defaultdict(list)
APIli = []
predli = []
for i in range(999):
    API_corelate[API_index_swap[i]] = [] 
    for j in range(len(Amatrix_test)):
        API_corelate[API_index_swap[i]].append(Amatrix_test.item(j, i))
   

In [84]:
corelate = {}
for api in range(999):
    var1 = API_corelate[API_index_swap[api]]
    corelate[API_index_swap[api]] = np.corrcoef(var1, preds)[0][1]
corelate   

/opt/conda/lib/python3.7/site-packages/numpy/lib/function_base.py:2530: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[:, None]
/opt/conda/lib/python3.7/site-packages/numpy/lib/function_base.py:2531: RuntimeWarning: invalid value encountered in true_divide
  c /= stddev[None, :]


{'Ljava/lang/String;->endsWith()Z': -0.2847012013596221,
 'Ljava/lang/String;->valueOf()Ljava/lang/String;': -0.05647403903659318,
 'Ljava/lang/StringBuilder;->append()Ljava/lang/StringBuilder;': 0.09265421410639206,
 'Ljava/lang/StringBuilder;->toString()Ljava/lang/String;': 0.09265421410639206,
 'Landroid/widget/ImageView;->setImageBitmap()V': -0.4062485148090687,
 'Landroid/util/Log;->a()I': -0.282915838072208,
 'Landroid/net/Uri;->parse()Landroid/net/Uri;': -0.26150967059229746,
 'Landroid/content/Intent;->setData()Landroid/content/Intent;': -0.3783568482754438,
 'Landroid/os/Environment;->getExternalStorageDirectory()Ljava/io/File;': -0.23382085989343754,
 'Landroid/graphics/Bitmap;->compress()Z': -0.35191086514159675,
 'Ljava/io/FileOutputStream;->flush()V': 0.00023486172611602045,
 'Ljava/io/FileOutputStream;->close()V': -0.049121362942430045,
 'Landroid/content/Intent;->setType()Landroid/content/Intent;': -0.4367401417879283,
 'Ljava/io/File;->getPath()Ljava/lang/String;': -0.1

In [ ]:
def sparse_corrcoef(A, B=None):

    if B is not None:
        A = sparse.vstack((A, B), format='csr')

    A = A.astype(np.float64)
    n = A.shape[1]

    # Compute the covariance matrix
    rowsum = A.sum(1)
    centering = rowsum.dot(rowsum.T.conjugate()) / n
    C = (A.dot(A.T.conjugate()) - centering) / (n - 1)

    # The correlation coefficients are given by
    # C_{i,j} / sqrt(C_{i} * C_{j})
    d = np.diag(C)
    coeffs = C / np.sqrt(np.outer(d, d))

    return coeffs

ABA = sparse_corrcoef(Amatrix_test.T)

In [99]:
ABA.shape

(332, 332)

In [104]:
ABA[331]

matrix([[0.18978765, 0.12136174, 0.08367395, 0.10426196, 0.10221458,
         0.13607592, 0.14266005, 0.11305178, 0.08954635, 0.29968139,
         0.11050048, 0.08269166, 0.09332315, 0.13580062, 0.18629709,
         0.0703019 , 0.08950446, 0.1198761 , 0.18748694, 0.08726905,
         0.07568823, 0.13241034, 0.14669834,        nan, 0.09146908,
         0.12897996, 0.12209173, 0.08327716, 0.0943913 , 0.15259007,
         0.11273103, 0.19955448, 0.09353007, 0.0938355 , 0.21012465,
         0.19502135, 0.13414229, 0.10049149, 0.09071183, 0.09042788,
         0.08733877, 0.09664814, 0.0832134 ,        nan, 0.11333299,
         0.07722538, 0.20669315,        nan, 0.095923  , 0.18489603,
         0.12024523, 0.10919802, 0.3020112 , 0.20799661, 0.27007575,
         0.1983408 , 0.25030702, 0.24437865, 0.28326096, 0.26118782,
         0.20799661, 0.26118782, 0.24437865, 0.25885526, 0.08886347,
         0.12974488, 0.10413686, 0.08368887, 0.12974488, 0.12347837,
         0.14437964, 0.2212253 , 0